## Notes
---------------------------------------------------
#### m(linhas) x n(colunas)

#### matriz 1x1 (unitária)
#### matriz 1xn (matriz linha)
#### matriz nx1 (matriz coluna)
---------------------------------------------------
#### retangulares m<>n
#### quadradas m=n
---------------------------------------------------
#### 1 - 0 - 0 - 2  ==> 1 - diagonal principal
#### 0 - 1 - 2 - 0  ==> 2 - diagonal secundaria
#### 0 - 2 - 1 - 0
#### 2 - 0 - 0 - 1   
---------------------------------------------------
#### 0 - 2 - 2 - 2   ==> 1 - matriz triangular inferior
#### 1 - 0 - 2 - 2   ==> 2 - matriz trinagular superior
#### 1 - 1 - 0 - 2
#### 1 - 1 - 1 - 0   
---------------------------------------------------
#### 1 - 0 - 0 - 0     ==> 1 - matriz diagonal(valores apenas em sua diagonal)
#### 0 - 1 - 0 - 0     
#### 0 - 0 - 1 - 0
#### 0 - 0 - 0 - 1   
---------------------------------------------------
#### 1 - 0 - 0 - 0     ==> 1 - matriz identidade (valores 1 em sua diagonal)
#### 0 - 1 - 0 - 0     
#### 0 - 0 - 1 - 0
#### 0 - 0 - 0 - 1   
---------------------------------------------------
#### 4 - 9 - 4 - 8     ==> -  matriz simétrica (valores simétricos independente se sua diagonal)
#### 9 - 1 - 1 - 0     
#### 4 - 1 - 5 - 2
#### 8 - 0 - 2 - 2   

In [1]:
# importação de modulo para algebra linear e aplicações matematicas
import numpy as np

In [ ]:
# criação de array(lista com valores) array de tecnologias

a1 = np.array(['spark', 'hadoop', 'python', 'R'])

In [ ]:
# visualização do array

a1

In [ ]:
# tipos diferentes no array
# array( [ [valuesx,...],[valuesy,...] ] ] )

a2 = np.array([['altura', 'largura', 'profundidade'], [23, 43, 10]])

In [ ]:
# visualização do array
a2

In [ ]:
# array appenas numeros

a3 = np.array([[14, 45, 54.7], [23, 43.9, 10]])

In [ ]:
# visualização do array

a3

In [ ]:
# tamanho dos arrays(.shape)

print(a1.shape)
print(a2.shape)
print(a3.shape)

In [ ]:
# dimensões dos array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

In [ ]:
# metodos para os arrays min, max 

a3.max(), a3.min()

In [ ]:
# metodo arrange, range de valores 0 a 19

array = np.arange(20)
array

In [ ]:
# valores de 0 a 100 passo 10

array = np.arange(0, 100, 10)
array

In [ ]:
# estruturas com linspace
# criação de um array de 20 elementos entre 0 e 10

matriz = np.linspace(0, 10, 20)
matriz

In [ ]:
matriz = np.linspace(0, 10, 5)
matriz

In [ ]:
matriz = np.linspace(0, 5, 5)
matriz

In [ ]:
# estruturas matrizes np.zeros( valores 0 ) ( (matriz mxn) )

matriz0 = np.zeros((10, 10))
matriz0

In [ ]:
# estruturas matrizes np.ones( valores 1 ) ( (matriz mxn) )

matriz1 = np.ones((10, 10))
matriz1

In [ ]:
# matriz identidade

matriz = np.eye(10)
matriz

In [ ]:
# matriz diagonal

matrizD = np.diag((0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20))
matrizD

In [5]:
# matriz empty

matriz = np.empty((10, 5))
matriz

array([[1.02228459e-311, 1.02228308e-311, 1.69121096e-306,
        3.30395829e-304, 4.45057637e-308],
       [7.56602523e-307, 6.23053614e-307, 2.22526399e-307,
        6.23053614e-307, 7.56592338e-307],
       [9.34581270e-307, 2.89275220e-307, 6.23056330e-307,
        1.78022342e-306, 8.06635958e-308],
       [1.05694828e-307, 1.39071360e-307, 1.27950405e-307,
        1.11262096e-307, 7.56563139e-307],
       [9.45700529e-308, 7.56561781e-307, 1.16820622e-307,
        8.90062138e-307, 1.16820622e-307],
       [9.79101761e-307, 9.34598925e-307, 8.90071136e-308,
        1.27950405e-307, 9.34598246e-307],
       [7.56594374e-307, 1.27945821e-307, 8.01057146e-307,
        9.45700529e-308, 1.33509015e-307],
       [9.79099724e-307, 9.34564294e-307, 1.00132483e-307,
        1.16824611e-307, 1.05695677e-307],
       [1.33508845e-307, 1.11258022e-307, 8.90062138e-307,
        7.56561780e-307, 1.11261926e-307],
       [1.16824781e-307, 9.34566332e-307, 1.11258192e-307,
        8.34424766e-308

In [7]:
# funções com arrays
# mutiplicação de arrays

np.tile(np.array([[1, 2], [3, 4], [5, 6]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [8]:
np.tile(np.array([[1, 2], [3, 4], [5, 6]]), (3, 6))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])