In [1]:
# tipagem de dados

In [2]:
import numpy as np

In [3]:
# definindo um array com tipo 'float'

a = np.array([-10, 10, 20, 23], dtype = 'float')

In [4]:
# visualizando o array

a

array([-10.,  10.,  20.,  23.])

In [5]:
# tipo do array

a.dtype

dtype('float64')

In [6]:
# definição array

b = np.array([25, 48, 10, 4, 5])
b.dtype

dtype('int32')

In [7]:
#  definição de array

c = np.array(['Café', 'pastel', 'cacau', 'sapato'])
c.dtype

dtype('<U6')

In [8]:
d = np.array([True, False, False, True])
d.dtype

dtype('bool')

In [9]:
# cast de arrays

f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [10]:
f.astype(int)

array([-9, 10, 20])

In [13]:
# operações com array

array = np.arange(0, 5) * 10
array

array([ 0, 10, 20, 30, 40])

In [14]:
array = np.arange(10) ** 2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
# operações entre arrays

arrayA = np.arange(0, 10)
arrayB = np.arange(0, 10)+1

In [16]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# soma entre os arrays

arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [20]:
arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [21]:
arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [22]:
# comparação entre arrays

arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [23]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [27]:
# tabela verdade

array1 = np.array([True, False, True, False])
array2 = np.array([False, False, True, False])

# comparação logica " and " entre os arrays
np.logical_and(array1, array2)

array([False, False,  True, False])

In [28]:
array1 = np.array([True, False, True, False])
array2 = np.array([False, False, True, False])

# comparação logica " or " entre os arrays
np.logical_or(array1, array2)

array([ True, False,  True, False])

In [29]:
# array com tamanhos diferentes

A = np.array([1, 2, 3, 4, 5])
B = np.array([1, 2, 3])

In [30]:
# soma com tamanhos diferentes

A + B

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [31]:
# multiplicação com tamanhos diferentes

A * B

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [32]:
# dot produto (multiplicação)

A = np.array([2, 4, 6])
B = np.array([2, 2, 2])

In [33]:
# hadmard 

A * B

array([ 4,  8, 12])

In [34]:
# dot product

print(np.dot(A, B))

24


In [35]:
A = np.array([3, 7, 10])
B = np.array([9, 3, 2])

In [36]:
A * B

array([27, 21, 20])

In [37]:
print(np.dot(A, B))

68


In [44]:
# copias e arrays

A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
B = A[5:]

In [46]:
B

array([5, 6, 7, 8, 9])

In [47]:
A[:] = 0

In [48]:
B

array([0, 0, 0, 0, 0])

In [51]:
A = np.arange(10)

In [52]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# forma correta para fazer uma copia

B = A[5:].copy()

In [54]:
B

array([5, 6, 7, 8, 9])

In [55]:
A[:] = 0

In [56]:
B

array([5, 6, 7, 8, 9])