In [1]:
import numpy as np

In [12]:
# lista
a = [2, 3, 11, 5, 14, 32, 12, 52, 51, 70, 20]
print(type(a))

# transformação array
array = np.array(a)

# impressão array
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
# tamanho do array
# (linhas, colunas)

array.shape

(11,)

In [14]:
# primeiro elemento do array

array[0]

2

In [15]:
# segundo elemento do array

array[1]

3

In [16]:
# ultimo elemento do array

array[-1]

20

In [17]:
# trazendo do indice 1 ao 5 (exclusivo) 5 elemento não vem

print(array[1:5])

[ 3 11  5 14]


In [18]:
# passo de 2 em 2 do 1 elemento até o 5 elemento

print(array[1:5:2])

[3 5]


In [21]:
# indices negativos
# -11 é o primeiro elemento e o elemento correspondente ao -3 (exclusivo) não vem 
array[-11:-3]

array([ 2,  3, 11,  5, 14, 32, 12, 52])

In [22]:
# do indice 2 até o final

array[2:]

array([11,  5, 14, 32, 12, 52, 51, 70, 20])

In [23]:
# do inicio até o indice 7
array[:7]

array([ 2,  3, 11,  5, 14, 32, 12])

In [24]:
# inversão do array retorna do ultimo ao primeiro 

array[::-1]

array([20, 70, 51, 52, 12, 32, 14,  5, 11,  3,  2])

In [25]:
# copiando o array por referencia
# alterações no array influenciam no b

b = array[:]
print(b)

[ 2  3 11  5 14 32 12 52 51 70 20]


In [27]:
# concatenando 2 arrays

x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 3, 5, 7, 9])
z = np.concatenate([x, y])

print(z)
print(type(z))

[ 2  4  6  8 10  1  3  5  7  9]
<class 'numpy.ndarray'>
