In [3]:
import numpy as np

In [4]:
# indexação de matrizes

In [5]:
# definindo a matriz

A = [[1, 2, 3, 4], 
    [11, 12, 13, 14], 
    [21, 22, 23, 24], 
    [31, 32, 33, 34]]

# array
array = np.array(A)

print(A)

# list
print(type(A))

[[1, 2, 3, 4], [11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]
<class 'list'>


In [6]:
# primeira linha

print(array[0]) 

[1 2 3 4]


In [7]:
# linha de indice 2

print(array[2])

[21 22 23 24]


In [8]:
# primeira linha ultima coluna

print(array[0, -1])

4


In [9]:
# atribuindo valor a uma posição da matriz

array[0, 0] = 9

# array modificado
print(array)

[[ 9  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [10]:
# atribuindo valor a coluna inteira 
array[:, -1] = 0

# array modificado
print(array)

[[ 9  2  3  0]
 [11 12 13  0]
 [21 22 23  0]
 [31 32 33  0]]


In [11]:
# intervalos
# numeros centrais 

print(array[1:3, 1:3])


[[12 13]
 [22 23]]


In [12]:
# intervalo 13, 23, 0, 0

print(array[1:3, 2:4])

[[13  0]
 [23  0]]


In [13]:
# somente a ultima coluna

print(array[:, -1])

[0 0 0 0]


In [14]:
# somente a ultima linha

print(array[-1])

[31 32 33  0]


In [15]:
# concatenando arrays multidimencionais

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])

C = np.concatenate((A, B))

print(C)

[[1 2]
 [3 4]
 [5 6]]
