In [1]:
# importação numpy

import numpy as np

In [2]:
# transposição 

A = np.array([[10, 20, 30], [40, 50, 60]])

In [3]:
# array

A 

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
# array transposto

A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [5]:
# transposição com transpose

np.transpose(A)

array([[10, 40],
       [20, 50],
       [30, 60]])

In [6]:
# array

B = np.array([[100, 200, 300]])

In [7]:
# array transposto

B.T

array([[100],
       [200],
       [300]])

In [8]:
# brodcasting

B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

In [9]:
# convertendo matrizes em array

A = np.array([np.arange(10, 60, 10), np.arange(100, 150, 10)])

In [10]:
# array

A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [11]:
# dimenções do array

A.shape

(2, 5)

In [12]:
# transformação de uma matriz em um vetor

A.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [13]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

In [14]:
# operadores logicos
# matriz com numeros aleatorios

array = np.random.randint(1, 10, size=(4, 4))

In [15]:
# matriz 

array

array([[2, 1, 3, 3],
       [4, 4, 2, 2],
       [7, 8, 5, 7],
       [8, 2, 5, 6]])

In [17]:
# any qualquer elemento (or)
# algum elemento é divisivel por 7

np.any((array % 7) == 0)

True

In [18]:
# all todos os elementos(and)
# todos os elementos menores que 11

np.all(array < 11)

True

In [19]:
# reshaping

array = np.arange(1, 16)

In [20]:
# array ordenado de 1 a 15

array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
# reshaping (3 linhas, 5 colunas)

array.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
# ordenando array

array = np.array([[3, 2], [10, -1]])

In [23]:
array

array([[ 3,  2],
       [10, -1]])

In [24]:
# ordenando por linhas (axis=1)

array.sort(axis= 1)

In [25]:
# array ordenando

array

array([[ 2,  3],
       [-1, 10]])

In [26]:
array = np.array([[3, 2], [10, -1]])

In [27]:
# ordenando por colunas

array.sort(axis=0)

In [28]:
# array ordenado por colunas

array

array([[ 3, -1],
       [10,  2]])