In [1]:
# importação numpy

import numpy as np

In [2]:
# matriz 2 dimensões
A = np.matrix(([1, 2], [3, 4]))

# matriz 2 dimensões
B = np.matrix(([5, 3], [8, 7]))

# array com 3 dimensões
Z = np.array([
    [[2, 6], [8, 4]],
    [[2, 6], [8,4 ]],
    [[2,6 ], [8, 4]]
])

# array 1 dimensão
Y = np.array([2, 6, 8, 4])

In [3]:
# matriz com mais de 2 dimensões não é suportado

Z = np.matrix([
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]],
    [[2, 4], [8, 4]]
])

ValueError: matrix must be 2-dimensional

In [4]:
# tipo da variavel A

print(type(A))

<class 'numpy.matrix'>


In [5]:
# tipo da variavel Z

print(type(Z))

<class 'numpy.ndarray'>


In [6]:
# tipo da variavel Y

print(type(Y))

<class 'numpy.ndarray'>


In [7]:
print(A)

[[1 2]
 [3 4]]


In [8]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [9]:
print(Y)

[2 6 8 4]


In [10]:
Z.shape

(3, 2, 2)

In [11]:
Y.shape

(4,)

In [12]:
# soma

print(A + B)

[[ 6  5]
 [11 11]]


In [13]:
print(B + 3)

[[ 8  6]
 [11 10]]


In [14]:
# subtração

print(A - B)

[[-4 -1]
 [-5 -3]]


In [15]:
# multiplicação

A = np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [16]:
# cruz

print(A * A)

[[ 7 10]
 [15 22]]


In [17]:
# indice a indice

print(np.multiply(A, A))

[[ 1  4]
 [ 9 16]]


In [18]:
# inversa

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
# importação do modulo linalg

from numpy.linalg import inv

In [20]:
# inversa 

print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
# transposta

print(A.T)

[[1 3]
 [2 4]]
